version: '3.7'

services:
  micro_game:
    build: ../../MicroGame
    container_name: micro_game
    ports:
      - "8080:8080"
    networks:
      - micro_network
    restart: always

  micro_social:
    build: ../../MicroSocial
    container_name: micro_social
    ports:
      - "8181:8181"
    networks:
      micro_network:
        ipv4_address: 172.18.0.101
    restart: always

  db_postgres_micro:
    image: postgres:latest
    container_name: db_postgres_micro
    ports:
      - "5432:5432"
    networks:
      - micro_network
    restart: always
    volumes:
      - db_data_micro:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=general-item
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  pgadmin_micro:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pg_admin_micro:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - micro_network
    restart: always

volumes:
  db_data_micro:
  pg_admin_micro:

networks:
  micro_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1